# Execute all the tests in the root folder without notification in docker using
# docker-compose
watch:
  root: src/Tests/
  regex: "Test.php"
  ignore_hidden: true
command:
  bin: docker-compose
  scope: all
  options:
    - exec
    - "-T"
    - php
    - bin/phpunit
notification:
  disable: true
