# Execute all the tests in the whole directory in docker using docker-compose
watch:
  root: src/Tests/
  regex: "Test.php"
  ignore_hidden: true
command:
  bin: docker-compose
  scope: dir
  options:
    - exec
    - "-T"
    - php
    - bin/phpunit
notification:
  img_failure: /home/hypnos/.testomatic/images/failure.png
  img_success: /home/hypnos/.testomatic/images/success.png
  regex_success: OK
  regex_failure: error
  display_result: false
