# Only execute the watched test
watch:
  root: src/Tests/
  regex: "Test.php"
  ignore:
    - src/Tests/_cache
    - src/Tests/_fixtures
  ignore_hidden: true
command:
  bin: bin/phpunit
  scope: current
notification:
  img_failure: /home/superUser/.testomatic/images/failure.png
  img_success: /home/superUser/.testomatic/images/success.png
  regex_success: OK
  regex_failure: error
  display_result: false
