testomatic:
  folder: src/Tests
  ext:
    - php
    - go
  command_path: docker-compose
  command_options:
    - exec
    - "-T"
    - 'php'
    - bin/phpunit
  notification:
    notify_img_failure: /home/superUser/.autotest/images/failure.png
    notify_img_success: /home/superUser/.autotest/images/success.png
    notify_success: OK
