watch:
  folder: src/Tests
  reg: "Test.php"
command:
  path: docker-compose
  options:
    - exec
    - "-T"
    - 'php'
    - bin/phpunit
notification:
  img_failure: /home/superUser/.autotest/images/failure.png
  img_success: /home/superUser/.autotest/images/success.png
  success: OK
  display_result: true
