# Execute all the project tests
watch:
  folder: ./
  regex: "_test.go"
  ignore:
    - vendor
  ignore_hidden: true
command:
  ignore_path: true
  options:
    - test
    - ./...
notification:
  img_failure: /home/superUser/.testomatic/images/failure.png
  img_success: /home/superUser/.testomatic/images/success.png
  regex_success: ok
  regex_failure: fail
  display_result: false
