watch:
  folder: ./...
  reg: _test.go
# possible: current, dir, all
command:
  path: go
  options:
    - test
notification:
  img_failure: /home/superUser/.autotest/images/failure.png
  img_success: /home/superUser/.autotest/images/success.png
  success: ok
  display_result: true
